export type Product = {
	id: string;
	name: string;
	category: string;
	price: number;
	regularPrice: number;
	onSale: boolean;
	hasOptions: boolean;
	image: string;
	imageLarge: string;
	sourceUrl: string;
	shortDescription: string;
	priceLabel: string;
};

export const catalogUpdatedAt = "2026-07-01T11:48:39.215Z";

export const products: Product[] = [
	{
		"id": "26096",
		"name": "Билет за семинар – „Медицинските гъби в подкрепа на женското здраве“",
		"category": "Билети",
		"price": 39.12,
		"regularPrice": 39.12,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2026/01/bilet-seminar-medicinski-gubi-zhensko-zdrave-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2026/01/bilet-seminar-medicinski-gubi-zhensko-zdrave-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bilet-seminar-medicinski-gubi-za-zhensko-zdrave/",
		"shortDescription": "Очаквайте скоро семинар „Медицинските гъби в подкрепа на женското здраве“. Моля, заплатете своя билет с банкова карта или по банков път, ако искате да го получите по електронен път. Ако желаете да получите билета си под формата на хартиено копие, може да го поръчате от сайта и с Наложен платеж (НП), но тогава се начислява такса доставка (до Ваш адрес или офис на СПИДИ).",
		"priceLabel": "20.00 &euro; (39.12 лв.)"
	},
	{
		"id": "2433",
		"name": "АЛОЕ АРБОРЕСЦЕНС подпомага стомашно-чревния баланс, 500 ml",
		"category": "Билкови продукти",
		"price": 62,
		"regularPrice": 62,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/04/aloe-arborescens-il-pucino-500-ml-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/04/aloe-arborescens-il-pucino-500-ml.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/aloe-arborescens-il-pucino/",
		"shortDescription": "500 ml",
		"priceLabel": "31.70 &euro; (62.00 лв.)"
	},
	{
		"id": "1849",
		"name": "АМИГДАЛИН подсилва защитата на организма, 100 капс. / 200 mg",
		"category": "Билкови продукти",
		"price": 62,
		"regularPrice": 62,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/amigdalin-vitamin-b17-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/amigdalin-vitamin-b17-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/amigdalin-vitamin-b17/",
		"shortDescription": "100 капсули по 200 mg Екстракт от кайсиеви ядки",
		"priceLabel": "31.70 &euro; (62.00 лв.)"
	},
	{
		"id": "1857",
		"name": "АНТИСТРЕС подходящ при стрес и безпокойство, 100 ml",
		"category": "Билкови продукти",
		"price": 20.93,
		"regularPrice": 20.93,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/dr-biomaster-antistress-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/dr-biomaster-antistress.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/dr-biomaster-antistress/",
		"shortDescription": "100 ml Хранителна добавка. 35% vol.",
		"priceLabel": "10.70 &euro; (20.93 лв.)"
	},
	{
		"id": "1853",
		"name": "ДЕТОКС за прочистване от вредни агенти, 135 капс. / 406 mg",
		"category": "Билкови продукти",
		"price": 43.81,
		"regularPrice": 43.81,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/dr-biomaster-detox-formula-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/dr-biomaster-detox-formula.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/dr-biomaster-detox-formula/",
		"shortDescription": "135 капсули по 406 mg Смес от набор екстракти и гъби на прах",
		"priceLabel": "22.40 &euro; (43.81 лв.)"
	},
	{
		"id": "1845",
		"name": "ЕСИАК при онкологични заболявания, 60 капс. / 500 mg",
		"category": "Билкови продукти",
		"price": 74.91,
		"regularPrice": 74.91,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/essiac-kapsuli-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/essiac-kapsuli-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/essiac-kapsuli/",
		"shortDescription": "60 капсули по 500 mg",
		"priceLabel": "38.30 &euro; (74.91 лв.)"
	},
	{
		"id": "1843",
		"name": "ЕСИАК ЧАЙ за подкрепа на имунната система, 42.5 g",
		"category": "Билкови продукти",
		"price": 64.93,
		"regularPrice": 64.93,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/essiac-tea-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/essiac-tea.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/essiac-prah/",
		"shortDescription": "42.5 g",
		"priceLabel": "33.20 &euro; (64.93 лв.)"
	},
	{
		"id": "1865",
		"name": "КАРАМФИЛ за пречистване на организма, 100 капс. / 400 mg",
		"category": "Билкови продукти",
		"price": 25.03,
		"regularPrice": 25.03,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/karamfil-kapsuli-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/karamfil-kapsuli.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/karamfil-kapsuli/",
		"shortDescription": "100 капсули по 400 mg 100% Карамфил ( Caryophyllus aromaticus ) на прах с желатинови капсули",
		"priceLabel": "12.80 &euro; (25.03 лв.)"
	},
	{
		"id": "1847",
		"name": "КУРКУМИН при възпалителни процеси, 60 капс. / 500 mg",
		"category": "Билкови продукти",
		"price": 55.15,
		"regularPrice": 55.15,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/dr-biomaster-kurkumin-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/dr-biomaster-kurkumin-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/kurkumin/",
		"shortDescription": "60 капсули пo 500 mg",
		"priceLabel": "28.20 &euro; (55.15 лв.)"
	},
	{
		"id": "1851",
		"name": "ПАУ Д`АРКО при бактериални и вирусни инфекции, 230 капс. / 370 mg",
		"category": "Билкови продукти",
		"price": 42.05,
		"regularPrice": 42.05,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/pau-darko-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/pau-darko.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/pau-darko/",
		"shortDescription": "230 капсули по 370 mg Екстракт от кора от Мравчено дърво 8:1 Подпомага имунната система и защитата на организма срещу вредни агенти",
		"priceLabel": "21.50 &euro; (42.05 лв.)"
	},
	{
		"id": "1841",
		"name": "СУПЕР ФОРМУЛА за сърце и кръвоносни съдове, 500 ml",
		"category": "Билкови продукти",
		"price": 37.94,
		"regularPrice": 37.94,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/super-formula-za-surce-i-kravonosni-sadove-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/super-formula-za-surce-i-kravonosni-sadove.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/super-formula-za-surce-kruvonosni-sudove/",
		"shortDescription": "Превъзходен натурален продукт, подпомагащ сърцето и кръвоносните съдове! Съдържа 22 билки в отлична комбинация!",
		"priceLabel": "19.40 &euro; (37.94 лв.)"
	},
	{
		"id": "1863",
		"name": "ТИНКТУРА ОТ ОРЕХ срещу патогенни агенти, 100 ml",
		"category": "Билкови продукти",
		"price": 27.97,
		"regularPrice": 27.97,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/tinktura-oreh-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/tinktura-oreh.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/tinktura-oreh/",
		"shortDescription": "100 ml 100% тинктура от обвивките (мезокарп) на орех ( Juglans regia ), супер силна",
		"priceLabel": "14.30 &euro; (27.97 лв.)"
	},
	{
		"id": "6756",
		"name": "Алое Вера – гел",
		"category": "Други продукти",
		"price": 33.05,
		"regularPrice": 33.05,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/aloe-vera-gel-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/aloe-vera-gel.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/aloe-vera-gel/",
		"shortDescription": "946 ml organic сертификат. Aloe Vera Gel 32 fl oz. Хранителна добавка.",
		"priceLabel": "16.90 &euro; (33.05 лв.)"
	},
	{
		"id": "6615",
		"name": "Бета глюкан – 1,3 D GLUCAN",
		"category": "Други продукти",
		"price": 150.01,
		"regularPrice": 150.01,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/beta-glucan-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/beta-glucan.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/beta-glucan/",
		"shortDescription": "60 капсули по 500 mg. Хранителна добавка.",
		"priceLabel": "76.70 &euro; (150.01 лв.)"
	},
	{
		"id": "6762",
		"name": "Био сода бикарбонат",
		"category": "Други продукти",
		"price": 3.13,
		"regularPrice": 3.13,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/soda-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/soda.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-soda-bikarbonat/",
		"shortDescription": "300 g",
		"priceLabel": "1.60 &euro; (3.13 лв.)"
	},
	{
		"id": "6760",
		"name": "Био Хуск – фибри",
		"category": "Други продукти",
		"price": 13.1,
		"regularPrice": 13.1,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/bio-husk-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/bio-husk.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-husk-fibri/",
		"shortDescription": "200 g",
		"priceLabel": "6.70 &euro; (13.10 лв.)"
	},
	{
		"id": "6753",
		"name": "Варбургия",
		"category": "Други продукти",
		"price": 21.12,
		"regularPrice": 21.12,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/warburgia-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/warburgia.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/warburgia/",
		"shortDescription": "60 капсули по 350 mg. Хранителна добавка.",
		"priceLabel": "10.80 &euro; (21.12 лв.)"
	},
	{
		"id": "6751",
		"name": "Витамин С на прах",
		"category": "Други продукти",
		"price": 9.78,
		"regularPrice": 9.78,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/vitamin-c-prah-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/vitamin-c-prah.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/vitamin-c-prah/",
		"shortDescription": "100 g. Хранителна добавка. 100% чист Витамин С на прах за по-бързо абсорбиране. Лесно разтворима формула!",
		"priceLabel": "5.00 &euro; (9.78 лв.)"
	},
	{
		"id": "6609",
		"name": "Клеева тинктура 30%",
		"category": "Други продукти",
		"price": 7.82,
		"regularPrice": 7.82,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/kleeva-tinktura-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/kleeva-tinktura.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/kleeva-tinktura/",
		"shortDescription": "50 ml. Хранителна добавка.",
		"priceLabel": "4.00 &euro; (7.82 лв.)"
	},
	{
		"id": "6666",
		"name": "Лактофлор – пробиотик",
		"category": "Други продукти",
		"price": 26.99,
		"regularPrice": 26.99,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/lactoflor-probiotic-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/lactoflor-probiotic.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/lactoflor-probiotic/",
		"shortDescription": "90 капсули. Хранителна добавка.",
		"priceLabel": "13.80 &euro; (26.99 лв.)"
	},
	{
		"id": "6668",
		"name": "Лактофлор Био плюс – пробиотик и пребиотик",
		"category": "Други продукти",
		"price": 24.06,
		"regularPrice": 24.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/lactoflor-bio-plus-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/lactoflor-bio-plus.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/lactoflor-bio-plus/",
		"shortDescription": "60 капсули. Хранителна добавка.",
		"priceLabel": "12.30 &euro; (24.06 лв.)"
	},
	{
		"id": "6648",
		"name": "Масло от черен кимион, 100 ml",
		"category": "Други продукти",
		"price": 22.1,
		"regularPrice": 22.1,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/maslo-cheren-kimion-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/maslo-cheren-kimion.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/maslo-cheren-kimion/",
		"shortDescription": "100 ml",
		"priceLabel": "11.30 &euro; (22.10 лв.)"
	},
	{
		"id": "6606",
		"name": "Омега 3-6-9",
		"category": "Други продукти",
		"price": 37.75,
		"regularPrice": 37.75,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/omega-3-6-9-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/omega-3-6-9.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/omega-3-6-9/",
		"shortDescription": "80 капсули 1200 mg. Хранителна добавка.",
		"priceLabel": "19.30 &euro; (37.75 лв.)"
	},
	{
		"id": "6637",
		"name": "Парапротекс (ParaproteX)",
		"category": "Други продукти",
		"price": 110.9,
		"regularPrice": 110.9,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/paraprotex-calivita-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/paraprotex-calivita.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paraprotex/",
		"shortDescription": "100 таблетки. Хранителна добавка.",
		"priceLabel": "56.70 &euro; (110.90 лв.)"
	},
	{
		"id": "6662",
		"name": "Рибено масло от сьомга, AboPharma, 1000 mg",
		"category": "Други продукти",
		"price": 18.58,
		"regularPrice": 18.58,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/ribeno-maslo-1000-mg-abo-pharma-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/ribeno-maslo-1000-mg-abo-pharma.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/ribeno-maslo-1000-mg-abo-pharma/",
		"shortDescription": "60 капсули по 1000 mg[:en]60 capsules of 1000 mg",
		"priceLabel": "9.50 &euro; (18.58 лв.)"
	},
	{
		"id": "6743",
		"name": "Сибирска чага – екстракт",
		"category": "Други продукти",
		"price": 41.07,
		"regularPrice": 41.07,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/sibirska-chaga-kapsuli-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/sibirska-chaga-kapsuli.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/sibirska-chaga-kapsuli/",
		"shortDescription": "90 растителни капсули 560 mg",
		"priceLabel": "21.00 &euro; (41.07 лв.)"
	},
	{
		"id": "6741",
		"name": "Сибирска чага – тинктура",
		"category": "Други продукти",
		"price": 14.67,
		"regularPrice": 14.67,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/03/sibirska-chaga-tinktura-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/03/sibirska-chaga-tinktura.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/sibirska-chaga-tinktura/",
		"shortDescription": "50 ml",
		"priceLabel": "7.50 &euro; (14.67 лв.)"
	},
	{
		"id": "27337",
		"name": "Конопът – забраненото лекарство",
		"category": "Книги",
		"price": 15.06,
		"regularPrice": 15.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2026/04/konopat-zabranenoto-lekarstvo-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2026/04/konopat-zabranenoto-lekarstvo.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/konopat-zabranenoto-lekarstvo/",
		"shortDescription": "Автори: Росица Тодорова, Християна Драгостинова Издателство: Распер, 2016 ISBN: 978-954-345-104-3",
		"priceLabel": "7.70 &euro; (15.06 лв.)"
	},
	{
		"id": "1898",
		"name": "Лечебната сила на гъбите – проф. Ян И. Лелей",
		"category": "Книги",
		"price": 19.95,
		"regularPrice": 19.95,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/lechebnata-sila-na-gubite-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/lechebnata-sila-na-gubite.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/lechebnata-sila-na-gubite/",
		"shortDescription": "Автор: проф. Ян Лелей Издател: Доктор Биомастер",
		"priceLabel": "10.20 &euro; (19.95 лв.)"
	},
	{
		"id": "1900",
		"name": "Лечебни гъби против рак и други заболявания",
		"category": "Книги",
		"price": 7.04,
		"regularPrice": 7.04,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/lechebni-gubi-rak-drugi-zabolqbaniq-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/lechebni-gubi-rak-drugi-zabolqbaniq.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/lechebni-gubi-rak-drugi-zabolqbaniq/",
		"shortDescription": "Автор: д-р Георги Георгиев Издател: Доктор Биомастер",
		"priceLabel": "3.60 &euro; (7.04 лв.)"
	},
	{
		"id": "1910",
		"name": "Лечението на всички напреднали форми на рак – д-р Хулда Кларк",
		"category": "Книги",
		"price": 25.03,
		"regularPrice": 25.03,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/lechenie-na-vsichki-naprednali-formi-na-rak-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/lechenie-na-vsichki-naprednali-formi-na-rak.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/lechenie-na-vsichki-naprednali-formi-na-rak/",
		"shortDescription": "Автор: д-р Хулда Кларк Издател: „Доктор Натура“",
		"priceLabel": "12.80 &euro; (25.03 лв.)"
	},
	{
		"id": "1904",
		"name": "Мост на надеждата – Джеймс У. Димърс",
		"category": "Книги",
		"price": 8.02,
		"regularPrice": 8.02,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/most-na-nadejdata-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/most-na-nadejdata.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/most-na-nadejdata/",
		"shortDescription": "Автор: Джеймс У. Димърс Издател: „Доктор Натура“",
		"priceLabel": "4.10 &euro; (8.02 лв.)"
	},
	{
		"id": "1914",
		"name": "Предпазване от всички видове рак – д-р Хулда Кларк",
		"category": "Книги",
		"price": 25.03,
		"regularPrice": 25.03,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/predpazvane-ot-vsichki-vidove-rak-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/predpazvane-ot-vsichki-vidove-rak.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/predpazvane-ot-vsichki-vidove-rak/",
		"shortDescription": "Автор: д-р Хулда Кларк Издател: „Доктор Биомастер“",
		"priceLabel": "12.80 &euro; (25.03 лв.)"
	},
	{
		"id": "2169",
		"name": "Рак и други тежки заболявания при домашните любимци",
		"category": "Книги",
		"price": 9.78,
		"regularPrice": 9.78,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/07/book-cancer-pets-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/07/book-cancer-pets.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/rak-drugi-zabolqvaniq-domashni-liubimci/",
		"shortDescription": "Автор: Борислав Пеев Издател: „ДОКТОР БИОМАСТЕР“",
		"priceLabel": "5.00 &euro; (9.78 лв.)"
	},
	{
		"id": "1902",
		"name": "Ракът може да бъде излекуван – Отец Романо Заго",
		"category": "Книги",
		"price": 7.04,
		"regularPrice": 7.04,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/rak-moje-da-bade-izlekuvan-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/rak-moje-da-bade-izlekuvan.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/rak-moje-da-bade-izlekuvan/",
		"shortDescription": "Автор: Отец Романо Заго, O.F.M. (от Ордена на францисканските монаси) Издател: Доктор Биомастер",
		"priceLabel": "3.60 &euro; (7.04 лв.)"
	},
	{
		"id": "1906",
		"name": "Сензационната антиракова диета на д-р Вулф Ласкин",
		"category": "Книги",
		"price": 8.02,
		"regularPrice": 8.02,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/senzacionnata-antirakova-dieta-vulf-laskin-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/senzacionnata-antirakova-dieta-vulf-laskin.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/senzacionnata-antirakova-dieta-vulf-laskin/",
		"shortDescription": "Автор: д-р Николай Колев Издател: „Доктор Натура“",
		"priceLabel": "4.10 &euro; (8.02 лв.)"
	},
	{
		"id": "2435",
		"name": "Комплект продукти и книга на д-р Хулда Кларк №1",
		"category": "Комплекти",
		"price": 62.43,
		"regularPrice": 78.04,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/04/komplekt-hulda-clark-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/04/komplekt-hulda-clark-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/komplekt-hulda-clark-1/",
		"shortDescription": "Комплект продукти по схемата на д-р Хулда Кларк и книга от автора.",
		"priceLabel": "39.90 &euro; (78.04 лв.) Original price was: 39.90&euro; (78.04 лв.). 31.92 &euro; (62.43 лв.) Текущата цена е: 31.92&euro; (62.43 лв.)."
	},
	{
		"id": "2439",
		"name": "Комплект продукти и книга на д-р Хулда Кларк №3",
		"category": "Комплекти",
		"price": 62.43,
		"regularPrice": 78.04,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/04/komplekt-hulda-clark-3-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/04/komplekt-hulda-clark-3.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/komplekt-hulda-clark-3/",
		"shortDescription": "Комплект продукти по схемата на д-р Хулда Кларк и книга от автора.",
		"priceLabel": "39.90 &euro; (78.04 лв.) Original price was: 39.90&euro; (78.04 лв.). 31.92 &euro; (62.43 лв.) Текущата цена е: 31.92&euro; (62.43 лв.)."
	},
	{
		"id": "1916",
		"name": "Предпазване от рак и лечение на напреднали форми на рак",
		"category": "Комплекти",
		"price": 37.55,
		"regularPrice": 50.07,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/10/predpazvane-rak-lechenie-naprednali-formi-rak-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/10/predpazvane-rak-lechenie-naprednali-formi-rak.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/predpazvane-rak-lechenie-naprednali-formi-rak/",
		"shortDescription": "Автор: д-р Хулда Кларк Издател: „Доктор Натура“",
		"priceLabel": "25.60 &euro; (50.07 лв.) Original price was: 25.60&euro; (50.07 лв.). 19.20 &euro; (37.55 лв.) Текущата цена е: 19.20&euro; (37.55 лв.)."
	},
	{
		"id": "2153",
		"name": "АГАРИКУС лекарствена гъба, Dr. Biomaster, 240 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 192.06,
		"regularPrice": 192.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/07/agarikus-blazei-extract-240-caps-2-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/07/agarikus-blazei-extract-240-caps-2.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/agarikus-blazei-extract-dr-biomaster-big/",
		"shortDescription": "240 капсули по 300 mg Екстракт от плодно тяло на гъба Агарикус Блазеи (Agaricus blazei Murrill)",
		"priceLabel": "98.20 &euro; (192.06 лв.)"
	},
	{
		"id": "1779",
		"name": "АГАРИКУС лекарствена гъба, Dr. Biomaster, 60 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/agaricus-blazei-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/agaricus-blazei-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/agarikus-blazei-extract-dr-biomaster/",
		"shortDescription": "60 капсули по 300 mg Екстракт от плодно тяло на гъба Агарикус Блазеи (Agaricus blazei Murrill)",
		"priceLabel": "32.70 &euro; (63.96 лв.)"
	},
	{
		"id": "1781",
		"name": "АГАРИКУС прахообразна формула от плодно тяло – 100 g",
		"category": "Лекарствени гъби",
		"price": 37.94,
		"regularPrice": 37.94,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/agaricus-prah-dr-biomaster-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/agaricus-prah-dr-biomaster.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/agaricus-blazei-prah-dr-biomaster/",
		"shortDescription": "100 g Прах от плодно тяло на гъба Агарикус Блазеи (Agaricus blazei Murrill)",
		"priceLabel": "19.40 &euro; (37.94 лв.)"
	},
	{
		"id": "1817",
		"name": "БИО АГАРИКУС лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/agaricus-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/agaricus-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/agaricus-blazei-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Агарикус ( Agaricus Subrufescens )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "14974",
		"name": "БИО АУРИКУЛАРИЯ лекарствена гъба, Hawlik, 240 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 203.99,
		"regularPrice": 203.99,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2024/10/aurikularia-hawlik-big-pack-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2024/10/aurikularia-hawlik-big-pack.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-auricularia-extract-hawlik-big/",
		"shortDescription": "240 капсули по 380 mg Екстракт от плодно тяло на гъба Аурикулария ( Auricularia polytricha )",
		"priceLabel": "104.30 &euro; (203.99 лв.)"
	},
	{
		"id": "1801",
		"name": "БИО АУРИКУЛАРИЯ лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/auricularia-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/auricularia-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-auricularia-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Аурикулария ( Auricularia polytricha )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "14987",
		"name": "БИО ГЪБА ШИЙТАКЕ, Hawlik, 240 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 203.99,
		"regularPrice": 203.99,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2024/10/shiitake-hawlik-big-pack-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2024/10/shiitake-hawlik-big-pack.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/shiitake-extract-hawlik-big/",
		"shortDescription": "240 капсули по 380 mg Екстракт от плодно тяло на гъба Шийтаке (Lentinula Edodes)",
		"priceLabel": "104.30 &euro; (203.99 лв.)"
	},
	{
		"id": "1825",
		"name": "БИО ГЪБИ ШИЙТАКЕ, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-shiitake-extract-hawlik-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-shiitake-extract-hawlik.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/shiitake-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодното тяло на гъби Шийтаке ( Lentinula Edodes )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "1811",
		"name": "БИО ЖЕНСКА СИЛА при менструални смущения, 90 капс. / 390 mg",
		"category": "Лекарствени гъби",
		"price": 64.93,
		"regularPrice": 64.93,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/jenska-sila-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/jenska-sila-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/jenska-sila/",
		"shortDescription": "90 капсули по 390 mg Екстракт от плодното тяло на гъбите Агарикус и Майтаке, както и прах от плодното тяло на гъбите Майтаке и Рейши",
		"priceLabel": "33.20 &euro; (64.93 лв.)"
	},
	{
		"id": "14983",
		"name": "БИО КОПРИНУС лекарствена гъба, Hawlik, 240 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 203.99,
		"regularPrice": 203.99,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2024/10/coprinus-hawlik-big-pack-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2024/10/coprinus-hawlik-big-pack.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-coprinus-extract-hawlik-big/",
		"shortDescription": "240 капсули по 380 mg Екстракт от плодно тяло на гъба Копринус ( Coprinus comatus )",
		"priceLabel": "104.30 &euro; (203.99 лв.)"
	},
	{
		"id": "1793",
		"name": "БИО КОПРИНУС лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/coprinus-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/coprinus-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-coprinus-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Копринус ( Coprinus comatus )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "1791",
		"name": "БИО КОРИОЛУС лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-coriolus-extract-60-caps-hawlik-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-coriolus-extract-60-caps-hawlik.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-coriolus-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Кориолус ( Coriolus versicolor ) Оставете ни запитване и ще бъдете автоматично уведомени при наличност.",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "1821",
		"name": "БИО МАЙТАКЕ гъба на капсули, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-maitake-extract-hawlik-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-maitake-extract-hawlik.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-meitake-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Майтаке ( Grifola Frondosa )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "14978",
		"name": "БИО ПОЛИПОРУС лекарствена гъба, Hawlik, 240 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 203.99,
		"regularPrice": 203.99,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2024/10/polyporys-hawlik-big-pack-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2024/10/polyporys-hawlik-big-pack.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/polyporus-extract-hawlik-big/",
		"shortDescription": "240 капсули по 380 mg Екстракт от плодно тяло на гъба Полипорус ( Polyporus umbellatus )",
		"priceLabel": "104.30 &euro; (203.99 лв.)"
	},
	{
		"id": "1805",
		"name": "БИО ПОЛИПОРУС лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/polyporus-hawlik-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/polyporus-hawlik-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/polyporus-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Полипорус ( Polyporus umbellatus )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "1823",
		"name": "БИО РЕЙШИ лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-reishi-extract-hawlik-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-reishi-extract-hawlik.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-reishi-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Рейши ( Ganoderma lucidum )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "1809",
		"name": "БИО РЕЛАКС при стрес и напрегнато ежедневие, 90 капс. / 375 mg",
		"category": "Лекарствени гъби",
		"price": 64.93,
		"regularPrice": 64.93,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-relax-hawlik-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/bio-relax-hawlik-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/relax/",
		"shortDescription": "90 капсули по 375 mg. Хранителна добавка. Прах от Био Рейши от плодно тяло, прах от Био Херициум от плодно тяло и екстракт от Био Кордицепс",
		"priceLabel": "33.20 &euro; (64.93 лв.)"
	},
	{
		"id": "1789",
		"name": "БИО ХЕРИЦИУМ лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/hericium-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/hericium-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/bio-hericium-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от плодно тяло на гъба Херициум ( Hericium erinaceus )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "1783",
		"name": "ГЪБА РЕЙШИ, Dr. Biomaster, 60 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/reishi-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/reishi-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/reishi-extract-dr-biomaster/",
		"shortDescription": "60 капсули по 300 mg Екстракт от плодно тяло на гъба Рейши (Ganoderma lucidum)",
		"priceLabel": "32.70 &euro; (63.96 лв.)"
	},
	{
		"id": "1739",
		"name": "ДИАФУНГИ при висока кръвна захар и диабет, 90 капс. / 330 mg",
		"category": "Лекарствени гъби",
		"price": 27.97,
		"regularPrice": 27.97,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/diafungi-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/diafungi.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/diafungi/",
		"shortDescription": "90 капсули по 330 mg Смес от прахове от плодно тяло на 3 лекарствени гъби: Майтаке ( Grifola frondosa ), Шийтаке ( Lentinula edodes ) и Копринус ( Coprinus comatus ).",
		"priceLabel": "14.30 &euro; (27.97 лв.)"
	},
	{
		"id": "259",
		"name": "ИМЮН МОДУЛАТОР за модулиране на имунната система, 90 капс. / 510 mg",
		"category": "Лекарствени гъби",
		"price": 109.92,
		"regularPrice": 109.92,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2016/08/imun-modulator-small-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2016/08/imun-modulator-small.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/imun-modulator-90-caps/",
		"shortDescription": "ИМЮН МОДУЛАТОР представлява смес от 6 лекарствени гъби и е отлично средство за подобряване функциите на имунната система.",
		"priceLabel": "56.20 &euro; (109.92 лв.)"
	},
	{
		"id": "1732",
		"name": "ИМЮН МОДУЛАТОР подкрепа при химиотерапия, 360 капс. / 510 mg",
		"category": "Лекарствени гъби",
		"price": 389.99,
		"regularPrice": 389.99,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/imun-modulator-big-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/imun-modulator-big.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/imun-modulator-360-caps/",
		"shortDescription": "ИМЮН МОДУЛАТОР представлява смес от 6 лекарствени гъби. Продуктът е съвместим с провеждането на химиотерапия и лъчетерапия.",
		"priceLabel": "199.40 &euro; (389.99 лв.)"
	},
	{
		"id": "1737",
		"name": "ИМЮНИТИ 365 за силен имунитет, 120 капс. / 520 mg",
		"category": "Лекарствени гъби",
		"price": 41.07,
		"regularPrice": 41.07,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/imunitet-365-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/imunitet-365.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/imunitet-365/",
		"shortDescription": "120 капсули по 520 mg Смес от 5 лекарствени гъби: Агарикус прах, Рейши прах, Майтаке прах, Шийтаке прах и Кордицепс екстракт.",
		"priceLabel": "21.00 &euro; (41.07 лв.)"
	},
	{
		"id": "1787",
		"name": "Кордицепс екстракт 60 капсули по 300 mg — Dr. Biomaster",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/cordyceps-extract-60-caps-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/cordyceps-extract-60-caps-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cordyceps-extract-dr-biomaster/",
		"shortDescription": "Екстракт от Cordyceps sinensis | 30% Полизахариди | Анализен сертификат от AGROLAB – Германия | Опаковка: 60 капсули по 300 мг | Оценка: ⭐⭐⭐⭐⭐ 4.97 / 5",
		"priceLabel": "32.70 &euro; (63.96 лв.)"
	},
	{
		"id": "2156",
		"name": "КОРДИЦЕПС лекарствена гъба, Dr. Biomaster, 240 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 192.06,
		"regularPrice": 192.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/07/cordyceps-extract-240-caps-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/07/cordyceps-extract-240-caps-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cordyceps-extract-dr-biomaster-big/",
		"shortDescription": "240 капсули по 300 mg Екстракт от мицел на гъба Кордицепс ( Cordyceps sinensis )",
		"priceLabel": "98.20 &euro; (192.06 лв.)"
	},
	{
		"id": "1819",
		"name": "КОРДИЦЕПС лекарствена гъба, Hawlik, 60 капс. / 380 mg",
		"category": "Лекарствени гъби",
		"price": 68.06,
		"regularPrice": 68.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/cordyceps-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/cordyceps-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cordyceps-extract-hawlik/",
		"shortDescription": "60 капсули по 380 mg Екстракт от мицел на гъба Кордицепс ( Cordyceps Sinensis )",
		"priceLabel": "34.80 &euro; (68.06 лв.)"
	},
	{
		"id": "2159",
		"name": "МАЙТАКЕ лекарствена гъба, Dr. Biomaster, 240 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 192.06,
		"regularPrice": 192.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/07/maitake-extract-240-caps-drbiomaster-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/07/maitake-extract-240-caps-drbiomaster.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/meitake-extract-dr-biomaster-big/",
		"shortDescription": "240 капсули по 300 mg Екстракт от плодно тяло на гъба Майтаке (Grifola frondosa)",
		"priceLabel": "98.20 &euro; (192.06 лв.)"
	},
	{
		"id": "1775",
		"name": "МАЙТАКЕ лекарствена гъба, Dr. Biomaster, 60 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/maitake-extract-2-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/maitake-extract-2.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/meitake-extract-dr-biomaster/",
		"shortDescription": "60 капсули по 300 mg Екстракт от плодно тяло на гъба Майтаке (Grifola frondosa)",
		"priceLabel": "32.70 &euro; (63.96 лв.)"
	},
	{
		"id": "1777",
		"name": "МАЙТАКЕ прахообразна формула от плодно тяло – 100 g",
		"category": "Лекарствени гъби",
		"price": 37.94,
		"regularPrice": 37.94,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/meitake-prah-dr-biomaster-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/meitake-prah-dr-biomaster.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/maitake-prah-dr-biomaster/",
		"shortDescription": "100 g Прах от плодно тяло на гъба Майтаке (Grifola frondosa)",
		"priceLabel": "19.40 &euro; (37.94 лв.)"
	},
	{
		"id": "4155",
		"name": "МЕШИМА лекарствена гъба, Dr. Biomaster, 60 капс. / 270 mg",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": true,
		"image": "https://drbiomaster.com/wp-content/uploads/2022/03/meshima-dr-biomaster-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2022/03/meshima-dr-biomaster.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/meshima-extract-dr-biomaster/",
		"shortDescription": "60 капсули по 270 mg Екстракт от плодното тяло на гъба Мешима (Phellinus linteus)",
		"priceLabel": "32.70 &euro; &ndash; 98.20 &euro; Price range: 32.70&euro; through 98.20&euro; (63.96 – 192.06 лв.)"
	},
	{
		"id": "1735",
		"name": "НАЙ-ДОБРАТА СМЕС ОТ ГЪБЕНИ ПРАХОВЕ с 9 витални гъби, 100 g",
		"category": "Лекарствени гъби",
		"price": 41.07,
		"regularPrice": 41.07,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/nai-dobrata-smes-gubeni-prahove-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/nai-dobrata-smes-gubeni-prahove.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/nai-dobrata-smes-gubeni-prahove/",
		"shortDescription": "100 g Смес от гъбените прахове от плодното тяло на 9 лекарствени гъби",
		"priceLabel": "21.00 &euro; (41.07 лв.)"
	},
	{
		"id": "2362",
		"name": "РЕЙШИ лекарствена гъба, Dr. Biomaster, 240 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 192.06,
		"regularPrice": 192.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/11/reishi-extract-240-caps-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/11/reishi-extract-240-caps-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/reishi-extract-dr-biomaster-big/",
		"shortDescription": "240 капсули по 300 mg Екстракт от плодно тяло на гъба Рейши (Ganoderma lucidum)",
		"priceLabel": "98.20 &euro; (192.06 лв.)"
	},
	{
		"id": "1785",
		"name": "РЕЙШИ прахообразна формула от плодно тяло – 100 g",
		"category": "Лекарствени гъби",
		"price": 37.94,
		"regularPrice": 37.94,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/reishi-prah-dr-biomaster-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/reishi-prah-dr-biomaster.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/reishi-prah-dr-biomaster/",
		"shortDescription": "100 g Прах от плодно тяло на гъба Рейши (Ganoderma lucidum)",
		"priceLabel": "19.40 &euro; (37.94 лв.)"
	},
	{
		"id": "2167",
		"name": "ХЕРИЦИУМ лекарствена гъба, Dr. Biomaster, 240 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 192.06,
		"regularPrice": 192.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/07/hericium-extract-240-caps-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/07/hericium-extract-240-caps-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/hericium-extract-dr-biomaster-big/",
		"shortDescription": "240 капсули по 300 mg Екстракт от плодно тяло на гъба Херициум ( Hericium Erinaceus )",
		"priceLabel": "98.20 &euro; (192.06 лв.)"
	},
	{
		"id": "2165",
		"name": "ХЕРИЦИУМ лекарствена гъба, Dr. Biomaster, 60 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2020/07/hericium-extract-60-caps-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2020/07/hericium-extract-60-caps.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/hericium-extract-dr-biomaster/",
		"shortDescription": "60 капсули по 300 mg Екстракт от плодно тяло на гъба Херициум ( Hericium Erinaceus )",
		"priceLabel": "32.70 &euro; (63.96 лв.)"
	},
	{
		"id": "2442",
		"name": "ШИЙТАКЕ лекарствена гъба, Dr. Biomaster, 240 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 192.06,
		"regularPrice": 192.06,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/04/shiitake-extract-240-caps-drbiomaster-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/04/shiitake-extract-240-caps-drbiomaster-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/shiitake-extract-dr-biomaster-big/",
		"shortDescription": "240 капсули по 300 mg Екстракт от плодно тяло на гъба Шиитаке (Lentinula edodes)",
		"priceLabel": "98.20 &euro; (192.06 лв.)"
	},
	{
		"id": "1771",
		"name": "ШИЙТАКЕ лекарствена гъба, Dr. Biomaster, 60 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 63.96,
		"regularPrice": 63.96,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/shiitake-extract-1-2-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/shiitake-extract-1-2.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/shiitake-extract-dr-biomaster/",
		"shortDescription": "60 капсули по 300 mg Екстракт от плодно тяло на гъба Шиитаке (Lentinula edodes)",
		"priceLabel": "32.70 &euro; (63.96 лв.)"
	},
	{
		"id": "1773",
		"name": "ШИЙТАКЕ прахообразна формула от плодно тяло – 100 g",
		"category": "Лекарствени гъби",
		"price": 37.94,
		"regularPrice": 37.94,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/shiitake-prah-drbiomaster-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/shiitake-prah-drbiomaster.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/shiitake-prah-dr-biomaster/",
		"shortDescription": "100 g Прах от плодно тяло на гъба Шийтаке (Lentinula edodes)",
		"priceLabel": "19.40 &euro; (37.94 лв.)"
	},
	{
		"id": "1769",
		"name": "ЯМАКИРО+ за по-добър метаболизъм 180 капс. / 300 mg",
		"category": "Лекарствени гъби",
		"price": 62,
		"regularPrice": 62,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2019/09/jamakiro-plus-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2019/09/jamakiro-plus.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/jamakiro/",
		"shortDescription": "180 капсули по 300 mg Смес от прахове от плодно тяло на 4 лекарствени гъби",
		"priceLabel": "31.70 &euro; (62.00 лв.)"
	},
	{
		"id": "24892",
		"name": "ПАКЕТ „АНТИСТРЕС“",
		"category": "Специални пакети",
		"price": 68.47,
		"regularPrice": 76.08,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-antistres-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-antistres.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-antistres/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 3.89€ (7.61 лв.)",
		"priceLabel": "38.90 &euro; (76.08 лв.) Original price was: 38.90&euro; (76.08 лв.). 35.01 &euro; (68.47 лв.) Текущата цена е: 35.01&euro; (68.47 лв.)."
	},
	{
		"id": "24886",
		"name": "ПАКЕТ „ЗДРАВИ КЛЕТКИ“",
		"category": "Специални пакети",
		"price": 204.36,
		"regularPrice": 227.07,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-zdravi-kletki-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-zdravi-kletki.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-zdravi-kletki/",
		"shortDescription": "Специална формула за подкрепа при по-тежки хронични и онкологични състояния ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 11.61€ (22.71 лв.)",
		"priceLabel": "116.10 &euro; (227.07 лв.) Original price was: 116.10&euro; (227.07 лв.). 104.49 &euro; (204.36 лв.) Текущата цена е: 104.49&euro; (204.36 лв.)."
	},
	{
		"id": "24747",
		"name": "ПАКЕТ „ИМУНИТЕТ“",
		"category": "Специални пакети",
		"price": 86.6,
		"regularPrice": 96.23,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-imunitet-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-imunitet.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-imunitet/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 4.92 € (9.63 лв.)",
		"priceLabel": "49.20 &euro; (96.23 лв.) Original price was: 49.20&euro; (96.23 лв.). 44.28 &euro; (86.60 лв.) Текущата цена е: 44.28&euro; (86.60 лв.)."
	},
	{
		"id": "24723",
		"name": "ПАКЕТ „МЕТАБОЛИЗЪМ И ИР“",
		"category": "Специални пакети",
		"price": 95.23,
		"regularPrice": 105.81,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-metabolism-i-ir-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-metabolism-i-ir.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-metabolism-i-ir/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 5.41€ (10.58 лв.)",
		"priceLabel": "54.10 &euro; (105.81 лв.) Original price was: 54.10&euro; (105.81 лв.). 48.69 &euro; (95.23 лв.) Текущата цена е: 48.69&euro; (95.23 лв.)."
	},
	{
		"id": "24728",
		"name": "ПАКЕТ „СТАВИ“",
		"category": "Специални пакети",
		"price": 96.29,
		"regularPrice": 106.98,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-stavi-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-stavi.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-stavi/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 5.47€ (10.69 лв.)",
		"priceLabel": "54.70 &euro; (106.98 лв.) Original price was: 54.70&euro; (106.98 лв.). 49.23 &euro; (96.29 лв.) Текущата цена е: 49.23&euro; (96.29 лв.)."
	},
	{
		"id": "24897",
		"name": "ПАКЕТ „СЪРДЕЧНО-СЪДОВА СИСТЕМА“",
		"category": "Специални пакети",
		"price": 91.71,
		"regularPrice": 101.9,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-surdechno-sudova-sistema-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-surdechno-sudova-sistema.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-surdechno-sudova-sistema/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 5.21€ (10.19 лв.)",
		"priceLabel": "52.10 &euro; (101.90 лв.) Original price was: 52.10&euro; (101.90 лв.). 46.89 &euro; (91.71 лв.) Текущата цена е: 46.89&euro; (91.71 лв.)."
	},
	{
		"id": "24743",
		"name": "ПАКЕТ „ХОРМОНАЛЕН БАЛАНС“",
		"category": "Специални пакети",
		"price": 115.12,
		"regularPrice": 127.91,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-hormonalen-balans-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-hormonalen-balans.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-hormonalen-balans/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 6.54€ (12.79 лв.)",
		"priceLabel": "65.40 &euro; (127.91 лв.) Original price was: 65.40&euro; (127.91 лв.). 58.86 &euro; (115.12 лв.) Текущата цена е: 58.86&euro; (115.12 лв.)."
	},
	{
		"id": "24882",
		"name": "ПАКЕТ „ХРАНОСМИЛАТЕЛНА СИСТЕМА“",
		"category": "Специални пакети",
		"price": 113.36,
		"regularPrice": 125.96,
		"onSale": true,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-hranismilatelna-sistema-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2025/12/specialen-paket-hranismilatelna-sistema.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/paket-hranismilatelna-sistema/",
		"shortDescription": "ВЗЕМЕТЕ СЕГА С 10% ОТСТЪПКА СПЕСТЯВАТЕ 6.44€ (12.60 лв.)",
		"priceLabel": "64.40 &euro; (125.96 лв.) Original price was: 64.40&euro; (125.96 лв.). 57.96 &euro; (113.36 лв.) Текущата цена е: 57.96&euro; (113.36 лв.)."
	},
	{
		"id": "8077",
		"name": "Куркумин и Конопено масло на капсули CANNABIMAX GOLD, 30 капсули",
		"category": "CBD масла",
		"price": 64.93,
		"regularPrice": 64.93,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2023/08/cannabimax-gold-drbiomaster-product-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2023/08/cannabimax-gold-drbiomaster-product.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cannabimax-gold/",
		"shortDescription": "Куркумин и конопено масло в двойна капсула",
		"priceLabel": "33.20 &euro; (64.93 лв.)"
	},
	{
		"id": "3252",
		"name": "CBD крем Alchemic Extracts, 800 mg CBD, 60 ml",
		"category": "CBD масла",
		"price": 85.08,
		"regularPrice": 85.08,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/12/alhimichen-krem-s-konop-800-cbd-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/12/alhimichen-krem-s-konop-800-cbd.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-krem-alchemic-extracts-800-mg/",
		"shortDescription": "",
		"priceLabel": "43.50 &euro; (85.08 лв.)"
	},
	{
		"id": "3276",
		"name": "CBD Масло на капсули CANNABIN Omega 5% – 500 mg CBD, 20 капс.",
		"category": "CBD масла",
		"price": 39.9,
		"regularPrice": 39.9,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/12/pbg-global-cannabin-omega-5-cbd-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/12/pbg-global-cannabin-omega-5-cbd.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-kapsuli-cannabin-omega-5-cbd-2/",
		"shortDescription": "",
		"priceLabel": "20.40 &euro; (39.90 лв.)"
	},
	{
		"id": "3058",
		"name": "CBD Масло CANNABIMAX EXTRA STRONG – 30% CBD, 10 ml",
		"category": "CBD масла",
		"price": 265.01,
		"regularPrice": 265.01,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/Strong1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/Strong1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cannabimax-extra-strong-30-cbd/",
		"shortDescription": "",
		"priceLabel": "135.50 &euro; (265.01 лв.)"
	},
	{
		"id": "3055",
		"name": "CBD Масло CANNABIMAX MEDIUM – 10% CBD, 10 ml",
		"category": "CBD масла",
		"price": 95.05,
		"regularPrice": 95.05,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/Medium1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/Medium1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cannabimax-medium-10-cbd/",
		"shortDescription": "",
		"priceLabel": "48.60 &euro; (95.05 лв.)"
	},
	{
		"id": "3053",
		"name": "CBD Масло CANNABIMAX SOFT – 5% CBD, 10 ml",
		"category": "CBD масла",
		"price": 55.15,
		"regularPrice": 55.15,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/Soft-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/Soft-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cannabimax-soft-5-cbd/",
		"shortDescription": "",
		"priceLabel": "28.20 &euro; (55.15 лв.)"
	},
	{
		"id": "3174",
		"name": "CBD Масло CIBDOL 1000 mg – 10% CBD, 10 ml",
		"category": "CBD масла",
		"price": 113.05,
		"regularPrice": 113.05,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-ot-konop-cibdol-10-cbd-1-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-ot-konop-cibdol-10-cbd-1.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cibdol-10-cbd/",
		"shortDescription": "",
		"priceLabel": "57.80 &euro; (113.05 лв.)"
	},
	{
		"id": "3176",
		"name": "CBD Масло CIBDOL 1500 mg – 15% CBD, 10 ml",
		"category": "CBD масла",
		"price": 165.07,
		"regularPrice": 165.07,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-ot-konop-cibdol-15-cbd-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-ot-konop-cibdol-15-cbd.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cibdol-15-cbd/",
		"shortDescription": "",
		"priceLabel": "84.40 &euro; (165.07 лв.)"
	},
	{
		"id": "3178",
		"name": "CBD Масло CIBDOL 2000 mg – 20% CBD, 10 ml",
		"category": "CBD масла",
		"price": 215.14,
		"regularPrice": 215.14,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-konop-cibdol-20-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-konop-cibdol-20.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cibdol-20-cbd/",
		"shortDescription": "",
		"priceLabel": "110.00 &euro; (215.14 лв.)"
	},
	{
		"id": "3170",
		"name": "CBD Масло CIBDOL 460 mg – 5% CBD, 10 ml",
		"category": "CBD масла",
		"price": 59.07,
		"regularPrice": 59.07,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-ot-konop-cibdol-5-cbd-new-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/maslo-ot-konop-cibdol-5-cbd-new.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-cibdol-5-cbd/",
		"shortDescription": "CIBDOL Масло от семената на индустриален коноп (Cannabis sativa L) 5%, 10 ml, 460 mg",
		"priceLabel": "30.20 &euro; (59.07 лв.)"
	},
	{
		"id": "3100",
		"name": "CBD Масло ENECTA BALANCED, 10% CBD, Енекта, 10 ml",
		"category": "CBD масла",
		"price": 62.98,
		"regularPrice": 62.98,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/hemp-extract-balanced-enecta-1000-mg-10-ml-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/hemp-extract-balanced-enecta-1000-mg-10-ml.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-enecta-10-cbd/",
		"shortDescription": "",
		"priceLabel": "32.20 &euro; (62.98 лв.)"
	},
	{
		"id": "3103",
		"name": "CBD Масло ENECTA STRONG, 24% CBD, Енекта, 10 ml",
		"category": "CBD масла",
		"price": 157.05,
		"regularPrice": 157.05,
		"onSale": false,
		"hasOptions": false,
		"image": "https://drbiomaster.com/wp-content/uploads/2021/11/hemp-extract-strong-enecta-24-cbd-2400-mg-10-ml-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2021/11/hemp-extract-strong-enecta-24-cbd-2400-mg-10-ml.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-maslo-enecta-24-cbd/",
		"shortDescription": "",
		"priceLabel": "80.30 &euro; (157.05 лв.)"
	},
	{
		"id": "26170",
		"name": "CBD тампони",
		"category": "CBD масла",
		"price": 14.39,
		"regularPrice": 14.39,
		"onSale": false,
		"hasOptions": true,
		"image": "https://drbiomaster.com/wp-content/uploads/2026/01/cbd-tamponi-daye-sredhno-absorbirashti-300x300.jpg",
		"imageLarge": "https://drbiomaster.com/wp-content/uploads/2026/01/cbd-tamponi-daye-sredhno-absorbirashti.jpg",
		"sourceUrl": "https://drbiomaster.com/produkti/cbd-tamponi/",
		"shortDescription": "Органичните тампони Daye, покрити с клинично тестван канабидиол (CBD), който съдържа 0.00% THC за ефективно, локализирано облекчаване на менструални спазми. Предлагат се два вида: обикновен размер и супер размер. 9 тампона в опаковка.",
		"priceLabel": "7.36 &euro; (14.39 лв.)"
	}
];
